services:
    tabby:
        build: .
        restart: always
        ports:
            - 9090:80
        environment:
            - PORT=80
            - DEBUG=False
            - DOCKERIZE_ARGS="-wait tcp://db:3306 -timeout 60s"
        # - APP_DIST_STORAGE="file:///app-dist"
