services:
    tabby:
        build: .
        restart: always
        ports:
            - 9090:80
        environment:
            - DATABASE_URL=mysql://root:K0stas1994@f8kkkw0:3306/default
            - PORT=80
            - DEBUG=False
