services:
    tabby:
        build: .
        restart: always
        ports:
            - 9090:80
        environment:
            - DATABASE_URL=mysql://user:K0stas1994@144.76.93.5:8465/default
            - PORT=80
            - DEBUG=False
